In [1]:
import pandas as pd
import numpy as np
import matplotlib as mp
%matplotlib inline

from sklearn import linear_model

In [2]:
train= pd.read_csv('train.csv')

In [3]:
train.head()

id cat1 cat2 cat3 cat4 cat5 cat6 cat7 cat8 cat9   ...        cont6  \
0   1    A    B    A    B    A    A    A    A    B   ...     0.718367   
1   2    A    B    A    A    A    A    A    A    B   ...     0.438917   
2   5    A    B    A    A    B    A    A    A    B   ...     0.289648   
3  10    B    B    A    B    A    A    A    A    B   ...     0.440945   
4  11    A    B    A    B    A    A    A    A    B   ...     0.178193   

      cont7    cont8    cont9   cont10    cont11    cont12    cont13  \
0  0.335060  0.30260  0.67135  0.83510  0.569745  0.594646  0.822493   
1  0.436585  0.60087  0.35127  0.43919  0.338312  0.366307  0.611431   
2  0.315545  0.27320  0.26076  0.32446  0.381398  0.373424  0.195709   
3  0.391128  0.31796  0.32128  0.44467  0.327915  0.321570  0.605077   
4  0.247408  0.24564  0.22089  0.21230  0.204687  0.202213  0.246011   

     cont14     loss  
0  0.714843  2213.18  
1  0.304496  1283.60  
2  0.774425  3005.09  
3  0.602642   939.85  
4  0.432606  2763.85  

[5 rows x 132 columns]

In [4]:
train.shape

(188318, 132)

In [5]:
train.describe()

id          cont1          cont2          cont3  \
count  188318.000000  188318.000000  188318.000000  188318.000000   
mean   294135.982561       0.493861       0.507188       0.498918   
std    169336.084867       0.187640       0.207202       0.202105   
min         1.000000       0.000016       0.001149       0.002634   
25%    147748.250000       0.346090       0.358319       0.336963   
50%    294539.500000       0.475784       0.555782       0.527991   
75%    440680.500000       0.623912       0.681761       0.634224   
max    587633.000000       0.984975       0.862654       0.944251   

               cont4          cont5          cont6          cont7  \
count  188318.000000  188318.000000  188318.000000  188318.000000   
mean        0.491812       0.487428       0.490945       0.484970   
std         0.211292       0.209027       0.205273       0.178450   
min         0.176921       0.281143       0.012683       0.069503   
25%         0.327354       0.281143       0.336105       0.350175   
50%         0.452887       0.422268       0.440945       0.438285   
75%         0.652072       0.643315       0.655021       0.591045   
max         0.954297       0.983674       0.997162       1.000000   

               cont8          cont9         cont10         cont11  \
count  188318.000000  188318.000000  188318.000000  188318.000000   
mean        0.486437       0.485506       0.498066       0.493511   
std         0.199370       0.181660       0.185877       0.209737   
min         0.236880       0.000080       0.000000       0.035321   
25%         0.312800       0.358970       0.364580       0.310961   
50%         0.441060       0.441450       0.461190       0.457203   
75%         0.623580       0.566820       0.614590       0.678924   
max         0.980200       0.995400       0.994980       0.998742   

              cont12         cont13         cont14           loss  
count  188318.000000  188318.000000  188318.000000  188318.000000  
mean        0.493150       0.493138       0.495717    3037.337686  
std         0.209427       0.212777       0.222488    2904.086186  
min         0.036232       0.000228       0.179722       0.670000  
25%         0.311661       0.315758       0.294610    1204.460000  
50%         0.462286       0.363547       0.407403    2115.570000  
75%         0.675759       0.689974       0.724623    3864.045000  
max         0.998484       0.988494       0.844848  121012.250000

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188318 entries, 0 to 188317
Columns: 132 entries, id to loss
dtypes: float64(15), int64(1), object(116)
memory usage: 189.7+ MB


In [7]:
print train.dtypes

id          int64
cat1       object
cat2       object
cat3       object
cat4       object
cat5       object
cat6       object
cat7       object
cat8       object
cat9       object
cat10      object
cat11      object
cat12      object
cat13      object
cat14      object
cat15      object
cat16      object
cat17      object
cat18      object
cat19      object
cat20      object
cat21      object
cat22      object
cat23      object
cat24      object
cat25      object
cat26      object
cat27      object
cat28      object
cat29      object
           ...   
cat102     object
cat103     object
cat104     object
cat105     object
cat106     object
cat107     object
cat108     object
cat109     object
cat110     object
cat111     object
cat112     object
cat113     object
cat114     object
cat115     object
cat116     object
cont1     float64
cont2     float64
cont3     float64
cont4     float64
cont5     float64
cont6     float64
cont7     float64
cont8     float64
cont9     float64
cont10    

In [8]:
# train[pd.isnull(train).any(axis=1)]
pd.isnull(train).any()

id        False
cat1      False
cat2      False
cat3      False
cat4      False
cat5      False
cat6      False
cat7      False
cat8      False
cat9      False
cat10     False
cat11     False
cat12     False
cat13     False
cat14     False
cat15     False
cat16     False
cat17     False
cat18     False
cat19     False
cat20     False
cat21     False
cat22     False
cat23     False
cat24     False
cat25     False
cat26     False
cat27     False
cat28     False
cat29     False
          ...  
cat102    False
cat103    False
cat104    False
cat105    False
cat106    False
cat107    False
cat108    False
cat109    False
cat110    False
cat111    False
cat112    False
cat113    False
cat114    False
cat115    False
cat116    False
cont1     False
cont2     False
cont3     False
cont4     False
cont5     False
cont6     False
cont7     False
cont8     False
cont9     False
cont10    False
cont11    False
cont12    False
cont13    False
cont14    False
loss      False
dtype: bool

# Data Preparation #

In [36]:
train.corr()

id     cont1     cont2     cont3     cont4     cont5     cont6  \
id      1.000000  0.002130  0.000783  0.000816  0.002578  0.000775  0.001426   
cont1   0.002130  1.000000 -0.085180 -0.445431  0.367549 -0.025230  0.758315   
cont2   0.000783 -0.085180  1.000000  0.455861  0.038693  0.191427  0.015864   
cont3   0.000816 -0.445431  0.455861  1.000000 -0.341633  0.089417 -0.349278   
cont4   0.002578  0.367549  0.038693 -0.341633  1.000000  0.163748  0.220932   
cont5   0.000775 -0.025230  0.191427  0.089417  0.163748  1.000000 -0.149810   
cont6   0.001426  0.758315  0.015864 -0.349278  0.220932 -0.149810  1.000000   
cont7   0.002209  0.367384  0.048187  0.097516 -0.115064 -0.249344  0.658918   
cont8   0.005534  0.361163  0.137468 -0.185432  0.528740  0.009015  0.437437   
cont9   0.001870  0.929912 -0.032729 -0.417054  0.328961 -0.088202  0.797544   
cont10  0.002582  0.808551  0.063526 -0.325562  0.283294 -0.064967  0.883351   
cont11  0.001075  0.596090  0.116824  0.025271  0.120927 -0.151548  0.773745   
cont12  0.000889  0.614225  0.106250  0.006111  0.130453 -0.148217  0.785144   
cont13  0.000442  0.534850  0.023335 -0.418203  0.179342 -0.082915  0.815091   
cont14 -0.004924  0.056688 -0.045584 -0.039592  0.017445 -0.021638  0.042178   
loss   -0.001122 -0.010237  0.141528  0.111053 -0.035831 -0.011355  0.040967   

           cont7     cont8     cont9    cont10    cont11    cont12    cont13  \
id      0.002209  0.005534  0.001870  0.002582  0.001075  0.000889  0.000442   
cont1   0.367384  0.361163  0.929912  0.808551  0.596090  0.614225  0.534850   
cont2   0.048187  0.137468 -0.032729  0.063526  0.116824  0.106250  0.023335   
cont3   0.097516 -0.185432 -0.417054 -0.325562  0.025271  0.006111 -0.418203   
cont4  -0.115064  0.528740  0.328961  0.283294  0.120927  0.130453  0.179342   
cont5  -0.249344  0.009015 -0.088202 -0.064967 -0.151548 -0.148217 -0.082915   
cont6   0.658918  0.437437  0.797544  0.883351  0.773745  0.785144  0.815091   
cont7   1.000000  0.142042  0.384343  0.492621  0.747108  0.742712  0.288395   
cont8   0.142042  1.000000  0.452658  0.336588  0.302381  0.315904  0.476402   
cont9   0.384343  0.452658  1.000000  0.785697  0.608000  0.626656  0.642028   
cont10  0.492621  0.336588  0.785697  1.000000  0.702896  0.713812  0.707876   
cont11  0.747108  0.302381  0.608000  0.702896  1.000000  0.994384  0.466247   
cont12  0.742712  0.315904  0.626656  0.713812  0.994384  1.000000  0.478677   
cont13  0.288395  0.476402  0.642028  0.707876  0.466247  0.478677  1.000000   
cont14  0.022286  0.043539  0.074154  0.041808  0.047293  0.050267  0.047543   
loss    0.119799  0.030508  0.014456  0.020236  0.099806  0.098724 -0.004022   

          cont14      loss  
id     -0.004924 -0.001122  
cont1   0.056688 -0.010237  
cont2  -0.045584  0.141528  
cont3  -0.039592  0.111053  
cont4   0.017445 -0.035831  
cont5  -0.021638 -0.011355  
cont6   0.042178  0.040967  
cont7   0.022286  0.119799  
cont8   0.043539  0.030508  
cont9   0.074154  0.014456  
cont10  0.041808  0.020236  
cont11  0.047293  0.099806  
cont12  0.050267  0.098724  
cont13  0.047543 -0.004022  
cont14  1.000000  0.019298  
loss    0.019298  1.000000

In [9]:
X = train.iloc[:,1:-15]
dummys=pd.get_dummies(X)

In [10]:
X2=train.iloc[:,-15:-1]

In [27]:
predictors=pd.concat([X2,dummys], axis=1)

cat1 cat2 cat3 cat4 cat5 cat6 cat7 cat8 cat9 cat10  ...   cat107 cat108  \
0    A    B    A    B    A    A    A    A    B     A  ...        J      G   
1    A    B    A    A    A    A    A    A    B     B  ...        K      K   
2    A    B    A    A    B    A    A    A    B     B  ...        F      A   
3    B    B    A    B    A    A    A    A    B     A  ...        K      K   
4    A    B    A    B    A    A    A    A    B     B  ...        G      B   

  cat109 cat110 cat111 cat112 cat113 cat114 cat115 cat116  
0     BU     BC      C     AS      S      A      O     LB  
1     BI     CQ      A     AV     BM      A      O     DP  
2     AB     DK      A      C     AF      A      I     GK  
3     BI     CS      C      N     AE      A      O     DJ  
4      H      C      C      Y     BM      A      K     CK  

[5 rows x 116 columns]

In [12]:
y = train.iloc[:,-1:]

# Modeling # 

In [13]:
import os
import matplotlib.pyplot as plt
import math
from sklearn.preprocessing import StandardScaler

In [14]:
x_standard = StandardScaler().fit_transform(predictors)
cov_mat = np.cov(x_standard.T)
eigenValues, eigenVectors = np.linalg.eig(cov_mat)
# print(eigenValues)
# print "\n"
# print(eigenVectors)

In [15]:
eig_pairs = [(np.abs(eigenValues[i]), eigenVectors[:,i])\
             for i in range(len(eigenValues))]

eig_pairs

[(17.721953237471244,
  array([  1.64860445e-01+0.j,  -7.33736241e-03+0.j,  -1.00254771e-01+0.j,
         ...,   6.22934923e-05+0.j,   1.83170544e-04+0.j,
           7.06106055e-04+0.j])),
 (13.329952185996426,
  array([-0.04135160+0.j,  0.01741688+0.j,  0.04990648+0.j, ...,
         -0.00081424+0.j, -0.00062610+0.j,  0.00141540+0.j])),
 (9.7175989683371249,
  array([ 0.00250819+0.j,  0.00961923+0.j,  0.01467218+0.j, ...,
          0.00100823+0.j,  0.00074743+0.j,  0.00182761+0.j])),
 (9.3736717438159332,
  array([ -9.24379854e-03+0.j,  -1.41683320e-03+0.j,  -4.05008159e-03+0.j,
         ...,   1.27670595e-05+0.j,  -7.42778982e-04+0.j,
          -2.93706553e-04+0.j])),
 (8.4775732098809566,
  array([-0.06945335+0.j, -0.05699143+0.j, -0.11836452+0.j, ...,
         -0.00253771+0.j, -0.00374870+0.j, -0.00619246+0.j])),
 (8.2925464462719312,
  array([  3.82146695e-02+0.j,   3.33562173e-03+0.j,   3.71520758e-02+0.j,
         ...,   7.83225645e-04+0.j,   3.51550315e-05+0.j,
           8.5407

In [31]:
from sklearn.decomposition import PCA

pca = PCA(n_components=4)
pca.fit(x_standard)

# print("The information (explained variance) \
# contained in each principal component: ", pca.explained_variance_ratio_)

# print "\n"

# print(pca.components_)



PCA(copy=True, n_components=4, whiten=False)

In [17]:
tot = sum(eigenValues)
var_exp = [(i / tot)*100 for i in sorted(eigenValues)]
cum_var_exp = np.cumsum(var_exp)

print(cum_var_exp)

[ -1.93007930e-15+0.j  -3.06203409e-15+0.j  -4.03683134e-15+0.j ...,
   9.73068742e+01+0.j   9.84629784e+01+0.j   1.00000000e+02+0.j]


In [25]:
print len(eigenVectors)
print len(eig_pairs)
print len(eigenValues)

1153
1153
1153


In [18]:
# from sklearn.neighbors import KNeighborsClassifier
# neigh = KNeighborsClassifier(n_neighbors=3)
# neigh.fit(X, y)
# KNeighborsClassifier(...)
# print(neigh.predict([[1.1]]))
# [0]
# print(neigh.predict_proba([[0.9]]))
# [[ 0.66666667  0.33333333]]